# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiOfsignal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 821)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: rgb(255, 170, 127);\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"  \n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
" \n"
"    \n"
"background-color: rgb(255, 170, 127);\n"
"    \n"
"color: rgb(255, 255, 255);\n"
"padding: 10px 10px;\n"
" \n"
" text-align: center;\n"
" \n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signalViewerLabel = QtWidgets.QLabel(self.centralwidget)
        self.signalViewerLabel.setStyleSheet("QLabel{\n"
"\n"
"    font: 75 26pt \"MS Serif\";\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"\n"
"}")
        self.signalViewerLabel.setObjectName("signalViewerLabel")
        self.gridLayout_2.addWidget(self.signalViewerLabel, 0, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, 15, -1, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setStyleSheet("QGraphicsView{\n"
"    background-color: rgb(24, 24, 24);\n"
"\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalScrollBar.setStyleSheet("QScrollBar{\n"
"background-color: rgb(255, 170, 127);\n"
"}")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_4.addWidget(self.horizontalScrollBar, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
" \n"
"    \n"
"background-color: rgb(255, 170, 127);\n"
"    \n"
"color: rgb(255, 255, 255);\n"
"\n"
" \n"
" text-align: center;\n"
" \n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.colourLabel = QtWidgets.QLabel(self.centralwidget)
        self.colourLabel.setStyleSheet("QLabel{\n"
"\n"
"    font: 75 18pt \"MS Serif\";\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"\n"
"}")
        self.colourLabel.setObjectName("colourLabel")
        self.gridLayout.addWidget(self.colourLabel, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.showHidenPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.showHidenPushButton.setObjectName("showHidenPushButton")
        self.verticalLayout.addWidget(self.showHidenPushButton)
        self.loadFilePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFilePushButton.setObjectName("loadFilePushButton")
        self.verticalLayout.addWidget(self.loadFilePushButton)
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setObjectName("startPushButton")
        self.verticalLayout.addWidget(self.startPushButton)
        self.pausePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pausePushButton.setObjectName("pausePushButton")
        self.verticalLayout.addWidget(self.pausePushButton)
        self.ResetPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetPushButton.setObjectName("ResetPushButton")
        self.verticalLayout.addWidget(self.ResetPushButton)
        self.clearPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearPushButton.setObjectName("clearPushButton")
        self.verticalLayout.addWidget(self.clearPushButton)
        self.speedPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.speedPushButton.setObjectName("speedPushButton")
        self.verticalLayout.addWidget(self.speedPushButton)
        self.zoomInPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInPushButton.setObjectName("zoomInPushButton")
        self.verticalLayout.addWidget(self.zoomInPushButton)
        self.zoomOutPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutPushButton.setObjectName("zoomOutPushButton")
        self.verticalLayout.addWidget(self.zoomOutPushButton)
        self.ClosePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClosePushButton.setObjectName("ClosePushButton")
        self.verticalLayout.addWidget(self.ClosePushButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 15)
        self.gridLayout_2.setColumnStretch(1, 85)
        self.gridLayout_2.setRowStretch(0, 10)
        self.gridLayout_2.setRowStretch(1, 90)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signal Viewer"))
        self.signalViewerLabel.setText(_translate("MainWindow", " Signal Viewer"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Wighte"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Green"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Red"))
        self.colourLabel.setText(_translate("MainWindow", "Colour"))
        self.showHidenPushButton.setText(_translate("MainWindow", "Show"))
        self.loadFilePushButton.setText(_translate("MainWindow", "Load File"))
        self.startPushButton.setText(_translate("MainWindow", "Start"))
        self.pausePushButton.setText(_translate("MainWindow", "Pause"))
        self.ResetPushButton.setText(_translate("MainWindow", "Reset"))
        self.clearPushButton.setText(_translate("MainWindow", "Clear"))
        self.speedPushButton.setText(_translate("MainWindow", "1x"))
        self.zoomInPushButton.setText(_translate("MainWindow", "Zoom_in_100%"))
        self.zoomOutPushButton.setText(_translate("MainWindow", "Zoom_out_100%"))
        self.ClosePushButton.setText(_translate("MainWindow", "Close"))
        





# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
